# -*- coding: utf-8 -*-
"""Assignment_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPZdLDK-Btz_OwwVyvc3rtGWk_AGhts0
"""

import streamlit as st
import numpy as np
import joblib

model = joblib.load("glass_classifier_model.pkl")
scaler = joblib.load("glass_scaler.pkl")

st.title("🔍 Glass Type Classifier")
st.markdown("This app predicts the **type of glass** based on its chemical composition using a trained ML model.")

RI = st.number_input("Refractive Index (RI)", value=1.52)
Na = st.number_input("Sodium (Na)", value=13.0)
Mg = st.number_input("Magnesium (Mg)", value=2.0)
Al = st.number_input("Aluminum (Al)", value=1.0)
Si = st.number_input("Silicon (Si)", value=72.0)
K = st.number_input("Potassium (K)", value=0.5)
Ca = st.number_input("Calcium (Ca)", value=8.5)
Ba = st.number_input("Barium (Ba)", value=0.0)
Fe = st.number_input("Iron (Fe)", value=0.0)

prediction = model.predict(input_scaled)[0]

glass_types = {
    1: "Building Windows (Float Process)",
    2: "Building Windows (Non Float Process)",
    3: "Vehicle Windows",
    4: "Containers",
    5: "Tableware",
    6: "Headlamps"
}

result = glass_types.get(prediction, "Unknown")
st.success(f"Predicted Glass Type: **{result} (Type {prediction})**")



